### ISSUE TITLE
browser add-in not working since last git pull

### ISSUE THREAD

**Issue by rborel** [fcturner/passwords#242] opened 2016-07-26 12:12 UTC
The update that fixed the 'Hung on Decrypting' issue seems to have broken the browser addin.

**Comment by fcturner** [comment] 2016-07-26 12:40
That's strange, but I don't support the addin. @eglia - Any ideas?

**Comment by eglia** [comment] 2016-07-31 10:39
This should be fixed with v0.3.4 of the Firefox addon. The problem is if the app fails to decrypt/parse the properties of an entry, the API will just return properties: false instead of an object. I added an additional check & a warning for this case.

**Comment by rborel** [comment] 2016-07-31 13:01
It appears to be fixed.   Thank you guys for your efforts on this
project.   Just need an android client..   Users...   Never satisfied....
;)

**Comment by intirix** [comment] 2016-07-31 13:06
@rborel Working on it ;)

**Closed** 2016-09-06 07:39 UTC
Labels: Addon/Extension related, bug
