### ISSUE TITLE
Can't Edit Information

### ISSUE THREAD

**Issue by kneiser** [fcturner/passwords#49] opened 2015-07-31 14:18 UTC
For some reason I can't edit any of the stored information (website, login name) or delete entries. The ownCloud edit icon appears as required, but when I click on it nothing happens. Otherwise the app works great. Am I doing something wrong? Is there a dependency missing? Currently using ownCloud V8.0.5 on Fedora 22 o/s.

**Comment by kneiser** [comment] 2015-07-31 14:27
I just checked the ownCloud admin log there are errors from the passwords app.


![screenshot 36](https://cloud.githubusercontent.com/assets/3117010/9009380/f5152694-375d-11e5-9af0-b08265a0061b.png)

**Comment by kneiser** [comment] 2015-07-31 14:31
Here are the ownCloud log entries:
[{"reqId":"6ec93d32f252e2f80324f5093b47fb92","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined index: extra_authentication at \/var\/www\/html\/owncloud\/apps\/passwords\/templates\/part.admin.php#21","level":3,"time":"2015-07-31T14:20:18+00:00"},{"reqId":"d0289fc5ba1bbc7db3e809bd7ba54f54","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"d0289fc5ba1bbc7db3e809bd7ba54f54","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"87c2e7e38533b4d765f7f96f5ebf8396","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"87c2e7e38533b4d765f7f96f5ebf8396","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"c0e857ffe4ca25115c3246e9c176c86e","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"c0e857ffe4ca25115c3246e9c176c86e","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"6dadac8237e8ef7d910ce44ee6d033a1","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"6dadac8237e8ef7d910ce44ee6d033a1","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"7225c5c925b413a3bfa334149e7c5c90","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"7225c5c925b413a3bfa334149e7c5c90","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"2379f6a81d30b051b01ec16adbb2c9f2","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"2379f6a81d30b051b01ec16adbb2c9f2","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:52:21+00:00"},{"reqId":"e892b65faa78d7be4d2dd6787a898739","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:53+00:00"},{"reqId":"e892b65faa78d7be4d2dd6787a898739","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:53+00:00"},{"reqId":"76112cd44eb558aff4d4b08df8267798","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:53+00:00"},{"reqId":"76112cd44eb558aff4d4b08df8267798","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:53+00:00"},{"reqId":"462dd7a8f3ac648e2564d901c8d9a869","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:53+00:00"},{"reqId":"462dd7a8f3ac648e2564d901c8d9a869","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:53+00:00"},{"reqId":"aa366c0fc5dbdf40ffa01543261baec9","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:52+00:00"},{"reqId":"aa366c0fc5dbdf40ffa01543261baec9","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:52+00:00"},{"reqId":"e0d11a63dbf623f69fffcd5f06ee7fac","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:52+00:00"},{"reqId":"e0d11a63dbf623f69fffcd5f06ee7fac","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:52+00:00"},{"reqId":"8e204ec561c6312e77745294cdef8611","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin2 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:52+00:00"},{"reqId":"8e204ec561c6312e77745294cdef8611","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined variable: admin1 at \/var\/www\/html\/owncloud\/apps\/passwords\/controller\/settingscontroller.php#49","level":3,"time":"2015-07-31T13:51:52+00:00"},{"reqId":"dd3c56643167b40c9b3a8e6c110f1cf4","remoteAddr":"10.25.3.121","app":"PHP","message":"Undefined index: extra_authentication at \/var\/www\/html\/owncloud\/apps\/passwords\/templates\/part.admin.php#21","level":3,"time":"2015-07-31T13:50:54+00:00"},{"reqId":"6f9aa60e73dd58e988e2f4579fbd6137","remoteAddr":"10.25.3.121","app":"core","message":"Invalid OCS content returned for app passwords","level":4,"time":"2015-07-31T13:50:48+00:00"},{"

**Comment by fcturner** [comment] 2015-07-31 17:25
I can't reproduce the undefined variable errors, but do have a clue. Migh be related to other unix systems. 
The edit error is already issues as #48. Thanks anyway!

**Comment by fcturner** [comment] 2015-08-01 12:44
Fixed as of release [8.0.8](https://github.com/fcturner/passwords/releases).

Thanks for reporting!

**Closed by fcturner** 2015-08-01 12:44 UTC
Labels: bug
