### ISSUE TITLE
SyntaxError: JSON.parse: expected double-quoted property name at line

### ISSUE THREAD

**Issue by Happyfeet01** [fcturner/passwords#299] opened 2016-12-15 19:05 UTC
After the Update all Passwords are at the Trash Folder. I must add them back to the active passwords folder. 
After login to the app i get these messages:

```
SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 40 of the JSON data (row 0):
{"website" : "Anja", "pass" : "false&quot;, false, &quot;deleted" : "false", "id" : "0", "user_id" : "Anja"}

`SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 42 of the JSON data (row 94):
{"website" : "idefix", "pass" : "false&quot;, false, &quot;deleted" : "false", "id" : "0", "user_id" : "idefix"}`
`SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 40 of the JSON data (row 96):
{"website" : "lars", "pass" : "false&quot;, false, &quot;deleted" : "false", "id" : "0", "user_id" : "lars"}`
```

Here is the nextcloud log:

```
Error	PHP	Uninitialized string offset: 1 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#624	2016-12-15T20:01:05+0100
Error	PHP	Uninitialized string offset: 1 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#624	2016-12-15T20:01:05+0100
Error	PHP	Undefined index: id at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#76	2016-12-15T19:59:20+0100
Error	PHP	Undefined index: id at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#50	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 98 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#42	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 98 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#39	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 98 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#38	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 98 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#37	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 98 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#36	2016-12-15T19:59:20+0100
Error	PHP	Undefined index: id at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#76	2016-12-15T19:59:20+0100
Error	PHP	Undefined index: id at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#50	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 97 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#42	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 97 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#39	2016-12-15T19:59:20+0100
Error	PHP	Undefined offset: 97 at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#38``
```

**Server Setup:**
Nextcloud 11 (stable)
PHP 7.0.13
Apache2

**Comment by chrsch** [comment] 2016-12-16 12:59
Same problem here with nextCloud 11.0 and passwords 19 installed from scratch

**Comment by fcturner** [comment] 2016-12-16 13:12
Thanks for reporting! NextCloud really doesn't like my app: wink:

**Comment by jiml8** [comment] 2016-12-18 05:18
I was going to report the same thing but I see it is already done.  I kind of regret jumping to NC11 from 10 now because I have a number of issues, and the passwords one is an important one.

Passwords are working, apparently.  I can create new ones and read the ones already in place.  Have not tried to alter ones already in place, or delete or anything like that.

The syntax errors indicate something is not going to work, though.

**Comment by jiml8** [comment] 2016-12-18 05:25
I should also note that my passwords did not go into the trash, they remained in place.

Also, when I look more closely at the error messages I am seeing, the referenced usernames/passwords appear to be usernames and passwords for the nextcloud users who use my installation, not my own website account information.  It is as if passwords is now accessing the owncloud user database.

Thus, this entry clearly belongs to my daughter:
SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 42 of the JSON data (row 45):
{"website" : "monica", "pass" : "false&quot;, false, &quot;deleted" : "", "id" : "0", "user_id" : "monica"}

and is not a username/password for any account that is mine.

Also to the best of my knowledge, my daughter is not using passwords on the nextcloud installation, though I do encourage her to do so.

I would guess we are seeing an issue associated with your recent logic to password protect the password page, based on the user login password.

**Comment by jiml8** [comment] 2016-12-18 05:28
For reference, this is Nextcloud 11 (fresh upgrade) running on Nas4Free 11 (FreeBSD11, php 7.something, lighttpd, sqlite3, everything up to date and recent)

**Comment by fcturner** [comment] 2016-12-18 05:45
Thanks for the info, that's really useful. Because this part...
{"website" : "monica", "pass" : "false", false, "deleted" : "", "id" : "0", "user_id" : "monica"}
...means that the error is caused by the parse of the user share list. That's why you're seeing her name: you are allowed to share with her. The error is thrown because of the 'false' value after '"pass" : "false"'. 

I'll look into this asap.

**Comment by chrsch** [comment] 2016-12-18 07:01
I could contribute a pull request, I identified the service where the data is read from db. I just don't have the time to reverse engineer what the json should actually look like and what should be placed at the position in the json where it says >false< now. So if you let me know, I'll go on :-)

**Comment by fcturner** [comment] 2016-12-23 10:39
Duplicate of #296 (will be solved there, but I'll let it know here if it's fixed too).

**Comment by elbotho** [comment] 2017-05-09 12:15
Issue should be solved in the newest master. More info at #297

**Comment by fcturner** [comment] 2017-05-09 14:26
:+1:

**Closed by fcturner** 2017-05-09 14:26 UTC
Labels: bug, duplicate
