### ISSUE TITLE
All passwords shown in "recycle bin" after each login

### ISSUE THREAD

**Issue by weipah** [fcturner/passwords#315] opened 2017-03-04 21:23 UTC
Each time I login I see all passwords in the recyle bin and none in the actual database.
Even when I recycle all the passwords, I can use them normaly and also use the search again. But after another login it appears the same.

Also creating new ones only creates them in trash bin, not under active passwords.

I'm on Nextcloud 11.0.2 and passwords app is v.20-beta7.

Are there maybe any logs I can provide for you?

I found these JS warnings/errors:
![image](https://cloud.githubusercontent.com/assets/1555658/23582359/aa1c25fc-0128-11e7-97ad-aefa0342cc89.png)

![image](https://cloud.githubusercontent.com/assets/1555658/23582361/ae9e76a2-0128-11e7-9909-d283861aff06.png)

**Comment by Stifi21** [comment] 2017-03-10 21:09
I have the same behavior within the same versions of Nextcloud 11.0.2 and passwords v.20-beta7 as weipah. Also saving a new password entry all old passwords move from active passwords to trash bin.

**Comment by Pyhrra** [comment] 2017-03-14 00:21
I am currently on 20-Beta7 and with Nextcloud 11.0.2 , and currently also experiencing this issue. 
Decrypts all passwords but its always goes back to the recycling bin after.

**Comment by marius-wieschollek** [comment] 2017-03-21 19:49
@weipah I think you may have the same issue as I do. The problem is that the deleted property of the password contains a string instead of a boolean and is not interpreted correctly. I created a pull request for this: #317. I would be happy if you could check if this works for you as well.

**Comment by weipah** [comment] 2017-03-22 10:00
Thanks @marius-wieschollek the fix works for me (20-Beta7 with NC 11.0.2).
[#317](https://github.com/fcturner/passwords/pull/317) looks good so.

**Comment by fcturner** [comment] 2017-03-23 08:20
This should now be fixed in the latest master. 

#### Package download
(remember to rename the folder to `passwords`)
[:package:ZIP file](../archive/master.zip)
[:package:TAR file](../archive/master.tar.gz)

#### Command line 
(assuming `/var/www/owncloud/` as your root location)
 ```sh
rm -rf /var/www/owncloud/apps/passwords
git clone https://github.com/fcturner/passwords.git /var/www/owncloud/apps/passwords
```

**Comment by fcturner** [comment] 2017-03-23 08:20
Thank you @marius-wieschollek 
Great work.

**Closed by fcturner** 2017-03-23 08:20 UTC
