### ISSUE TITLE
Possibility to create passwords groups

### ISSUE THREAD

**Issue by Andrew908** [fcturner/passwords#29] opened 2015-07-08 22:29 UTC
In order to better manage the passwords it would be very useful to create groups and alocate different types of passwords to that group. This would also require a name field instead of just the website/company field in order to better identify the passwords. For example to group password for different services on the same server. 

And it would also be appreciated if you can star out also the usernames in order to avoid curios people.

Kind regards,

**Comment by fcturner** [comment] 2015-07-09 08:45
Thank you for this input. 

The groups addition will be implemented with (duplicate) #13. 

Crossing out the username would be an option on the Personal page, great idea. Then I will add an option for crossing out passwords as well (I really don't like the feature, but apparently others do). 

Thanks again! :smile:

**Comment by Andrew908** [comment] 2015-07-09 09:23
Thank you, but I wanted to ask you about the name column instead of having only website or company and modify the website column in an URL column ( as it is in Keepass). 

I would also make a suggestion regarding the possibility of adding an expiration date of the passwords. ( depending on whether a user wants or no to add an expiration date, one year ) or at least for the moment to be able to change from the interface the 150 days and 365 days intervals.

**Comment by fcturner** [comment] 2015-07-09 11:01
Regarding your first point, I will look into this later. 

For the latter, you can create a new issue for this (I will do it for you now). Thanks for the idea!

**Comment by fcturner** [comment] 2015-07-26 13:39
Crossing out user names and passwords: fixed with the 8.0.6 release (https://github.com/fcturner/passwords/commit/aa76297a04e9f3d18bf5ff189aa8bbc531e7a174)

Group suggestion is duplicate of #13, so this can be closed.

**Closed by fcturner** 2015-07-26 13:39 UTC
Labels: duplicate
